name: Merge Ready

on: pull_request_target

# Declare default permissions as read only.
permissions: {}

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - uses: angular/dev-infra/github-actions/unified-status-check@836bdd0543d15904c469f5a0ce869d30a8029971
        with:
          angular-robot-key: ${{ secrets.ANGULAR_ROBOT_PRIVATE_KEY }}
